spring.application.name=BoardNew
#HikariCP 데이터 소스(DataSource)
#spring.datasource.hikari.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.hikari.jdbc-url=jdbc:log4jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.hikari.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.hikari.jdbc-url=jdbc:log4jdbc:mariadb://localhost:3306/board2?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.hikari.username=root
spring.datasource.hikari.password=asdf1234
spring.datasource.hikari.connection-test-query=SELECT NOW() FROM dual
   
#MyBatis 5. 마이바티스 SELECT 컬럼과 DTO 멤버 변수 매핑하기 map-underscore-to-comel-case
mybatis.configuration.map-underscore-to-camel-case=true


# change upload file size
spring.servlet.multipart.maxFileSize=10MB
spring.servlet.multipart.maxRequestSize=50MB

#logging.level.org.springframework=DEBUG
#logging.level.com.study=DEBUG


#logging.level.org.springframework=DEBUG
#logging.level.org.springframework.boot=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.beans=TRACE